#!bin/bash
ascii(){
    printf "%d" "'$1"
}
chr() {
  [ "$1" -lt 256 ] || return 1
  printf "\\$(printf '%03o' "$1")"
}
# A-Z
a(){
    local variable=$(shuf -i 65-90 -n 1)
    echo $variable
}
#1-9
b(){
    local variable=$(shuf -i 48-57 -n 1)
    echo $variable
}
#a-z
c(){
    local variable=$(shuf -i 97-122 -n 1)
    echo $variable
}
number=0 
while [ $((3444-$number)) -gt 0 ]
do
    AZ=$($(chr $(shuf -i 97-99 -n 1)))
    letter=$(echo $(chr $AZ))
    printf "%s" "$letter"
    number=$(($number+$AZ))
done
last=$((3566-$number ))
letter=$(echo $(chr $last))
printf "%s\n" "$letter"
#printf $(($number+$last))
